Linear Regression: {}
Lasso:
  alpha: [0.001, 0.01, 0.1, 1, 10]
Ridge:
  alpha: [0.001, 0.01, 0.1, 1, 10]
K-Neighbors Regressor:
  n_neighbors: [3, 5, 7, 9]
SVR:
  kernel: ["rbf", "linear"]
  C: [0.1, 1, 10, 100]
  epsilon: [0.01, 0.1, 0.5, 1]
  gamma: ["scale", "auto"]
Random Forest Regressor:
  n_estimators: [100, 200]
  max_depth: [null, 10, 20]
  min_samples_split: [2, 5]
XGBRegressor:
  n_estimators: [100, 200]
  max_depth: [3, 5, 7]
  learning_rate: [0.01, 0.1, 0.2]
CatBoosting Regressor:
  depth: [4, 6, 8]
  learning_rate: [0.01, 0.1, 0.2]
  iterations: [250, 500]
AdaBoost Regressor:
  n_estimators: [50, 100, 200]
  learning_rate: [0.01, 0.1, 1]
